### ISSUE TITLE
parallelizing the build process

### ISSUE THREAD

**Issue by Pyroluk** [laurolins/nanocube#30]
Hello,

We at YP Mobile Labs are currently working with this interesting technology to visualize some of our datasets.
We compiled ourselves a nc_q25_c1_c1_c1_c1_c1_c1_c1_c1_c1_c1_c1_c1_u2_u4 cube, which works fine, but it takes approximately two weeks to put ~200M points in it.
How can we speed up the building process? We thought about multithreading the building process. If that is a suitable way, can you guys provide us with some information and tips on how to do this in the best way possible?

**Comment by laurolins** [comment]
Wow! We never tried such a high dimensional nanocube before. That is interesting. A simple rule of thumb when thinking about these nanocubes/datacubes is that its size will be proportional to the number of “product bins” that the data “touches”/“hits". For example if a “device” dimension has a “bin" called “iPhone”, and a dimension “language” has a “bin" called “english”, then a record with “iPhone” and “english” values will hit the product bin “(iPhone, english)”. This product bin will need to be represented in the data structure to account for such record. The number of “product bins” grows exponentially with the number of dimension in a nanocube, so, unless the there is a lot of correlation of which "product bins” are hit by the data, we should expect a rapid growth in the nanocube size as well. The time to prepare a nanocube is proportional to its size, so I am curious if your nanocube is actually fitting in RAM (didn't it swap out to disk, making the process which is already slow, even slower?). 

If we assume a (high-dimensional) nanocube we want to build is small enough to fit in main memory and we want to speed up the insertion process, the idea of multi-threaded insertion is a possibility. The problem I see with multi-threading is that every two records we insert in a nanocube share resources (e.g. the global aggregation is hit by all records) and a lot of thread contention might occur. It is also tricky to get the locks in the right places in the insertion algorithm. 

Another possibility which might be faster than the multi-threaded insertion could be to partition the data, build multiple partial nanocubes using the simpler contention free single-threaded approach, and then merge pairs of partial nanocubes until we get to a final one.

Yet another idea is to partition the data, create independent nanocubs with each part of the data, and, at query time, issue the same query to all nanocubes and then merge their results. Depending on the number of parts, the overhead at query time might not be too bad.

**Comment by Pyroluk** [comment]
Hello again,

I spend some time to think about combining two nanocubes and came up with the following pseudocode:
```
Combine(Node A, Node B, int dimension)
{
	foreach(Childnode CA in A.childs)
	{
		Childnode CB = B.childs[CA.Lable];
		
		if(CB == null)
		{
			CB = new Node(CA.Lable);
			B.childs.add(CB);
		}
		//only in Flattree?
		else if(CB.isSharedChild)
		{
			CB = shallowCopy(CB);
			B.childs[CA.Lable] = CB;
		}
		
		Combine(Node A, Node B, int dimension);
	}
	
	//Add Content from Node A to Node B
	
	bool isLastDimension = dimension == dim(S);
	
	if(B.childs.count == 1) {
		setSharedContent(B.Content, B.childs[0].Content);
		return;	//nothing more to do for this node
	}
	else if(B.Content.isSharedContent)
		B.Content = isLastDimension ? copySummedTableTimeSeries(B.Content) : shallowCopy(B.Content);
	else if(B.Content == null)
		B.Content = isLastDimension ? new SummedTableTimeSeries() : new Node();
	
	if(isLastDimension) 				//Copy SummedTableTimeSeries Objects from Node A to Node B
		foreach(Object o in A.Content)
			B.Content.add(o);//Problem: Add only new objects!
	else								//Combine the Content from Node A into Node B
		Combine(A.Content, B.Content, dimension + 1);
}
```
Problems that I see:
- B.Content.add(o); needs to skip objects that have already been added to the SummedTableTimeSeries. This problem exists if nodes have a shared relationship/connection. For instance if you combine nanocube #5 into nanocube #3 in Fig. 2 of the nanocube paper. In the last step the content of the two root nodes will be combined. While traversing the flat tree in nanocube #3, shallowCopy will copy the Android node of cube #3 with the address (0,1; 01,10; Android). Later copySummedTableTimeSeries() will copy the SummedTableTimeSeries of that node. This SummedTableTimeSeries already contains the Objects from nanocube #5 (same address), therefore they don’t need to be copied again from the Content of the root of nanocube #5.
- Traversing the nanocube in a recursive manner might be too costly.

What do you guys think?

**Comment by laurolins** [comment]
Hi pyroluk,
Seeing your effort to merge two nanocubes made me reflect again on the
problem. My current view is that although it would be great to have an
efficient merging algorithm, the problem is challenging and might not
payoff. Just so that you know, the basic insertion algorithm we have
in the paper and our current repo is not optimal in terms of memory
usage for the general case (i.e. multiple dimensions with multiple
levels). We worked out a proof and implementation of an optimal
insertion algorithm and it is a tricky business. The main problem for
an optimal insert is that at some point, in the natual insertion
logic, we need to decide whether we can share a certain node or copy
the info of that node. In general, the correct decision cannot be
found locally and involves distant parts of the data structure. If you
remember the yellow-green-colored action in the video I sent you
before, that is the optimal insertion algorithm proving which decision
is the correct one: sharing or duplicating. We are soon going to add a
new branch at our public repo with a complete new nanocube
implementation that contains the optimal algorithm and other features
(e.g. the ability to quickly save and retrieve nanocubes from
disk). So, back to your question, I think the problem of correctly
merging two nanocubes given the non-local aspect of the shared
pointers is tricky and will result in a not-so-efficient and
not-so-simple algorithm. Trying to speed up the optimal-insert version
we have now, in my view, is a more important problem to solve at the
moment. Our current approach to speed up insertion is to partition the
data into multiple space-efficient-nanocubes, query them all and merge
the results. An overhead in query time, but gives us the flexibility
of potentially distributing the data in multiple places and speeds up
the insertion.

**Comment by Pyroluk** [comment]
Hi Lauro,

I'd love to contribute to this project by speeding up the optimal-insert algorithm.
Would it be possible to become a part of your nanocube team?
I’m a computer science student from Germany, currently working for YP Mobile Labs, New York City.
I would like to write my bachelor thesis about this topic, if you have some work left for me.

**Comment by laurolins** [comment]
Cool! Our lab is also in NYC, shoot me an email so that we can schedule a study session over an efficient and optimal-insertion algorithm.
