### ISSUE TITLE
Web client stops when time slider brush moves outside of data range

### ISSUE THREAD

**Issue by markwynter** [laurolins/nanocube#35]
I've installed Nanocubes 3.2.1, and Chicago crime data.
There appears to be a bug when playing around with the time slider - particularly if
you move the time slider brush outside of the plotted data range - at this stage all interactive controls stop working and need to hit page refresh.  It happens in both Chrome and Safari. Haven't test firefox.
Temporary demo site here:
http://52.64.86.244/nanocube/

**Comment by jklosow** [comment]
Hi, Mark.  Sorry for the trouble you're having.  I accessed your nanocube but was unable to reproduce your bug in any of the three browsers (firefox, chrome, safari).  Perhaps I'm misunderstanding what you are doing.  After map and data loaded, I used the mouse to select a subset of time (about a week from Feb 16 to Feb 23).  The heatmap and bar charts adjust to this selection of data as expected.  I then slide the time series to the left to expose dates in March (which have no data).  Then I slide the week selection window over so that it starts around March 16 (see image).
![crimesselection](https://cloud.githubusercontent.com/assets/3332418/9762942/bc0d3d5a-56d4-11e5-9f43-2511d8f3c6fa.jpg)

As expected, the bar charts and heatmap go blank, as there is no data in this selection window.  However, I'm able to move the selection window back (or even delete it), and I get back to showing the data again (see image). 

![crimesselection2](https://cloud.githubusercontent.com/assets/3332418/9762967/e366c934-56d4-11e5-9dea-a416d62a2bfa.jpg)

It sounds to me like this is where things break for you.  You are unable to get any interactions to work at this point and so have to reload the page.  Is that correct?

I will try loading 3.2.1 to see if I can reproduce it directly there.  Will let you know.

Jim

**Comment by markwynter** [comment]
Hi Jim...  Thanks for looking into this.   Definitely something going on ... here is a series of screenshots in sequence order. ... the last image clearly shows the viewer has stopped responding...  The histogram still shows despite no time series data, and nothing happens if you click on a histogram or elsewhere on the timeline.  Hopefully you can replicate the issue.
<img width="1214" alt="screen shot 2015-09-10 at 8 11 11 am" src="https://cloud.githubusercontent.com/assets/10004552/9776139/883a90de-5794-11e5-9005-ab9f94640fc6.png">
<img width="1204" alt="screen shot 2015-09-10 at 8 11 53 am" src="https://cloud.githubusercontent.com/assets/10004552/9776149/9c22c1ca-5794-11e5-9507-4c0efc012ef6.png">
<img width="1204" alt="screen shot 2015-09-10 at 8 14 17 am" src="https://cloud.githubusercontent.com/assets/10004552/9776170/becca3f8-5794-11e5-833d-0230579a4e6a.png">

**Comment by salivian** [comment]
Hi Mark,

Please pull the latest version and see if you can reproduce the problem.
The web client was trying to query the server with a negative time.

Thanks for letting us know.

Horace

**Comment by markwynter** [comment]
Thanks Horace - the problem now seems to be fixed.  Thanks so much for your responsiveness.  I'm really looking forward to working with nanocubes :-)
