### ISSUE TITLE
Any considerations behind the 8 bit limit for categorical dimensions?

### ISSUE THREAD

**Issue by hy9be** [laurolins/nanocube#66]
I noticed there is a hard coded 8 bit limit (cardinality < 256?) for categorical dimensions [here](https://github.com/laurolins/nanocube/blob/master/src/nanocube/nanocube_csv.c#L743-L751). What is the reason behind that? Is it safe to enlarge it to 16bit or 32bit?

**Comment by laurolins** [comment]
Every dimension in a nanocube is encoded as a tree. We made the design choice of allowing the maximum degree of a node to be 256 (2^8). To encode a wider categorical dimension you should use the levels parameter. Instead of a categorical dimension with 1 level of 8 bits, you can go to 2 levels of 8 bits and be able to encode 65536 categorical values (i.e. the leaves of this two level tree).
